# Generated by Django 4.0.4 on 2022-09-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.CharField(max_length=300, verbose_name='Ответ'),
        ),
    ]
