# Generated by Django 4.1.2 on 2022-12-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('mail', models.CharField(max_length=150, verbose_name='Почта')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('address_autoschool', models.CharField(choices=[('Москва', 'Большая Тульская ул., 2, 8 офис; 2 этаж, Москва, 115191'), ('Москва', 'улица Казакова д6 стр1, Москва, 105064'), ('Москва', 'Петровка ул., 15с1, Москва, 107031')], max_length=200, verbose_name='Адрес автошколы')),
                ('category', models.CharField(choices=[('Еда', 'Еда'), ('Места', 'Места'), ('Еда', 'Еда'), ('Места', 'Места'), ('Еда', 'Еда'), ('Места', 'Места'), ('Еда', 'Еда'), ('Места', 'Места'), ('Еда', 'Еда'), ('Места', 'Места')], max_length=100, verbose_name='Категория')),
                ('group', models.CharField(choices=[('Группа 3', 'Начало обучения 30.06.2023'), ('Группа 2', 'Начало обучения 15.04.2023'), ('Группа 1', 'Начало обучения 07.01.2023')], max_length=100, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Форма',
            },
        ),
    ]
