# Generated by Django 4.1.2 on 2022-12-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='address_autoschool',
            field=models.CharField(choices=[('Москва', 'Петровка ул., 15с1, Москва, 107031'), ('Москва', 'Большая Тульская ул., 2, 8 офис; 2 этаж, Москва, 115191'), ('Москва', 'улица Казакова д6 стр1, Москва, 105064')], max_length=200, verbose_name='Адрес автошколы'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Категория B', 'Категория B'), ('Категория A', 'Категория A'), ('Категория BE', 'Категория BE'), ('Категория A1', 'Категория A1'), ('Категория C', 'Категория C'), ('Подкатегория C1', 'Подкатегория C1'), ('Экстремальное вождение', 'Экстремальное вождение'), ('Ралли', 'Ралли'), ('Дрифт', 'Дрифт'), ('Специализированные программы', 'Специализированные программы')], max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='group',
            field=models.CharField(choices=[('Группа 2', 'Начало обучения 15.04.2023'), ('Группа 1', 'Начало обучения 07.01.2023'), ('Группа 3', 'Начало обучения 30.06.2023')], max_length=100, verbose_name='Группа'),
        ),
    ]
