# Generated by Django 4.1.2 on 2022-12-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_ticket_address_autoschool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='address_autoschool',
            field=models.CharField(choices=[('Москва', 'Петровка ул., 15с1, Москва, 107031'), ('Москва', 'улица Казакова д6 стр1, Москва, 105064'), ('Москва', 'Большая Тульская ул., 2, 8 офис; 2 этаж, Москва, 115191')], max_length=200, verbose_name='Адрес автошколы'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='group',
            field=models.CharField(choices=[('Группа 3', 'Начало обучения 30.06.2023'), ('Группа 1', 'Начало обучения 07.01.2023'), ('Группа 2', 'Начало обучения 15.04.2023')], max_length=100, verbose_name='Группа'),
        ),
    ]
