# Generated by Django 4.0.4 on 2022-09-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_faqs_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('pagelink', models.CharField(max_length=15, verbose_name='Ссылка на категорию')),
                ('imglink', models.URLField(verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Параметры категорий',
                'verbose_name_plural': 'Параметры',
            },
        ),
    ]
