# Generated by Django 4.1.2 on 2022-10-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_faqs_question 2'),
        ('school', '0004_cards'),
        ('school', '0004_cards 2'),
    ]

    operations = [
    ]
