# Generated by Django 4.0.4 on 2022-09-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_boat_pagelink_alter_cards_pagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
