# Generated by Django 4.0.4 on 2022-09-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_boat_id_alter_cards_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boat',
        ),
    ]
