# Generated by Django 4.0.4 on 2022-09-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_delete_boat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extreme',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('pagelink', models.CharField(max_length=30, verbose_name='Ссылка на категорию')),
                ('imglink', models.URLField(verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Экстрим',
                'verbose_name_plural': 'Экстримальное вождение',
            },
        ),
    ]
