# Generated by Django 4.1.2 on 2022-10-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('price_min', models.CharField(max_length=10, null=True, verbose_name='Минимальная цена')),
                ('price_mid', models.CharField(max_length=10, null=True, verbose_name='Средняя цена')),
                ('price_high', models.CharField(max_length=10, null=True, verbose_name='Максимальная цена')),
                ('description_min', models.CharField(max_length=300, null=True, verbose_name='Описание минимальной')),
                ('description_mid', models.CharField(max_length=300, null=True, verbose_name='Описание средней')),
                ('description_high', models.CharField(max_length=300, null=True, verbose_name='Описание максимальной')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация о категориях',
            },
        ),
    ]
