# Generated by Django 4.0.4 on 2022-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('pagelink', models.CharField(max_length=30, verbose_name='Ссылка на категорию')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('price_min', models.CharField(max_length=10, verbose_name='Минимальная цена')),
                ('price_mid', models.CharField(max_length=10, verbose_name='Средняя цена')),
                ('price_high', models.CharField(max_length=10, verbose_name='Максимальная цена')),
                ('description_min', models.CharField(max_length=300, verbose_name='Описание минимальной')),
                ('description_mid', models.CharField(max_length=300, verbose_name='Описание средней')),
                ('description_high', models.CharField(max_length=300, verbose_name='Описание максимальной')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация о категориях',
            },
        ),
    ]
