# Generated by Django 4.0.4 on 2022-09-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
