# Generated by Django 4.1.2 on 2022-10-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0002_alter_info_id'),
        ('description', '0002_alter_info_id 2'),
    ]

    operations = [
    ]
