# Generated by Django 4.0.4 on 2022-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_faqs_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.CharField(max_length=100, verbose_name='Вопрос'),
        ),
    ]
