# Generated by Django 4.0.4 on 2022-09-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_boat_alter_cards_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='pagelink',
            field=models.CharField(max_length=30, verbose_name='Ссылка на категорию'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='pagelink',
            field=models.CharField(max_length=30, verbose_name='Ссылка на категорию'),
        ),
    ]
